### ISSUE TITLE
lvs script should be able to import xschem netlist

### ISSUE THREAD

**Issue by proppy** [google/globalfoundries-pdk-libs-gf180mcu_fd_pr#101]
By default xschem extract netlist with the `.spice` extension and include modeling equation as part of the parameters (which klayout can't parse).

It would be nice if the lvs script was trying multiple extension and simplifying the netlist prior to parsing.

**Comment by StefanSchippers** [comment]
If needed this can be easily done in xschem. 
for each mos symbol add a `lvs_format` attribute in addition to the `format` attribute that is used for simulation netlists:
`lvs_format="@name @pinlist @model L=@L W=@W nf=@nf m=@m"`
This will generate in the LVS netlist (Simulation->LVS netlist is checked) only the parameters that are relevant for LVS:

`M1 D G S B nfet_03v3 L=0.28u W=0.22u nf=1 m=1`

The above example also does not use the @spiceprefix attribute so MOS transistors will be netlisted as MOSFETS (Mxxxx... lines) instead of subcircuits (XMxxx... lines).

**Comment by proppy** [comment]
@StefanSchippers that's awesome! (and would be way cleaner than removing the argument as part of the LVS script like #99 is attempting to do)

**Comment by proppy** [comment]
@atorkmabrains @mithro we should consider adding `lvs_format` attribute to the primitive symbols in https://github.com/google/globalfoundries-pdk-libs-gf180mcu_fd_pr/tree/main/cells/xschem/symbols

**Comment by atorkmabrains** [comment]
@proppy yes
